language:
- clojure

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

sudo: false

before_install:
- ./scripts/devhelpers/setup.sh
- mkdir -p $HOME/.lein
- echo '{:user {:plugins [[jonase/eastwood "0.2.3"]]}}' > $HOME/.lein/profiles.clj


script:
- lein do clean, check, test :all, eastwood '{:source-paths ["src" "test"]}'
